replicas: 1
image:
  repository: 225047281420.dkr.ecr.ap-northeast-2.amazonaws.com/client
  tag: 1.2.7
  imagePullSecrets:
    - name: ecr-cred
service:
  # type: NodePort
  protocol: TCP
  targetPort: 3000
  port: 3000
  # nodePort: 31081
ingress:
  enabled: false
