replicas: 1
image:
  repository: 225047281420.dkr.ecr.ap-northeast-2.amazonaws.com/client
  tag: 1.1.4
  imagePullSecrets:
    - name: ecr-cred
service:
  type: NodePort
  protocol: TCP
  targetPort: 8080
  port: 8080
  nodePort: 31081
ingress:
  enabled: false
