apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 80
{{- with  .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetProt }}
  selector:
    app: client
